language:
    python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
    mkdir /var/log/cpapi
    chown www-data /var/log/cpapi
    cpapiweb/run.py
after_success:
    coveralls
